micronaut:
  application:
    name: demo
---
#tag::mongodb[]
mongodb:
#  uri: mongodb://mongo1:27017,mongo2:27017,mongo3:27017
  uri: mongodb://user:secret@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/test
#end::mongodb[]
---
#tag::db[]
db:
  name: 'test'
  collection: 'fruits'